// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy8_oL8VoFoJFD_N3YmQ3xlJESwNwS2UU',
    appId: '1:715905940754:web:f911f2106c4b7e871107cb',
    messagingSenderId: '715905940754',
    projectId: 'student-attendance-94b12',
    authDomain: 'student-attendance-94b12.firebaseapp.com',
    storageBucket: 'student-attendance-94b12.firebasestorage.app',
    measurementId: 'G-5BK2L7QYZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCis2GOL5f6zNd0D0cEDQ5_nuZmbAuzz9I',
    appId: '1:715905940754:android:e201f6642b0fdba31107cb',
    messagingSenderId: '715905940754',
    projectId: 'student-attendance-94b12',
    storageBucket: 'student-attendance-94b12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZVg786acdBuvxwKRDX806VGz5am6H-kw',
    appId: '1:715905940754:ios:b096705630b83c3b1107cb',
    messagingSenderId: '715905940754',
    projectId: 'student-attendance-94b12',
    storageBucket: 'student-attendance-94b12.firebasestorage.app',
    iosBundleId: 'com.example.studentAttendance',
  );
}
